[package]
name = "bravia-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
restman-rs = { version = "0.1.0", path = "../restman-rs" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
